name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    environment: release
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: build
      shell: bash
      run: |
        python -m pip install --upgrade build
        python -m pip install -r requirements-dev.txt
        python -m build

    - name: make schema
      shell: bash
      run: |
        python -m level4.model schema -o schema.json


    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          schema.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
